---
title: "Week05"
author: "CXiao"
date: "5/1/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Load library  
```{r message = F, warning = F}
library(tidyverse)
library(Hmisc)
library(maps)
```

### Read in data  
```{r message = F, warning = F}
dfASC <- read_csv("data/acs2015_county_data.csv")
```

### County Map data
```{r}
Upper1  <- function(x){
  substr(x, 1, 1) <- toupper(substr(x, 1, 1))
  x
}

cnty <- map_data("county")%>%
  as_tibble()%>%
  rename(State = region, County = subregion) %>%
  mutate(County = str_replace(County, "Dona Ana", "Doña Ana")) 

dfASC <- dfASC%>%
  select(CensusId:County, MeanCommute)


head(cnty)
```

### Join Map and ASC
```{r}
# cnty has 48 states and DC
# ASC has all 50 States, DC and PR
cntyASC <- left_join(cnty, dfASC, by = c("State", "County"))

stASC   <- dfASC %>%
  group_by(State) %>%
  summarise(MeanCommute = sum(MeanCommute * TotalPop)/sum(TotalPop))
```

### Find out missing counties
```{r}
cntyMiss <- cntyASC%>%
  filter(is.na(MeanCommute))%>%
  group_by(State, County)%>%
  summarise(Missing = 1)

cntyMiss %>% as.data.frame()
# https://en.wikipedia.org/wiki/De_Kalb,_Missouri
# https://en.wikipedia.org/wiki/DeKalb_County,_Alabama
```

## Counties Plot  
### CONUS Plot
```{r message = F, warning = F, fig.width = 10}
p <- ggplot(cnty, aes(long, lat, group = group)) + 
  geom_polygon(data = cntyASC, aes(fill = MeanCommute), 
 #              show.legend = FALSE, 
               colour = "grey") + 
  coord_quickmap()+
  scale_fill_distiller(palette = "Spectral")+
  theme_void()+
  labs(title = "Commute Time (min)",
       caption = "Cource: US Census Demogrpahic Data 2015")
p
```


### plotly  
```{r message = F, warning = F, fig.width = 10}
library(plotly)
#ggplotly(p)
```

### `choroplethr` framework  
```{r message = F, warning = F}
# https://bookdown.org/rdpeng/RProgDA/mapping.html#mapping-us-counties-and-states
# https://github.com/trulia/choroplethr
library(choroplethr)
library(choroplethrMaps)
data(df_pop_county)

# https://twitter.com/nlj/status/991149834085289984
mean_commute <- dfASC %>%
  select(CensusId, MeanCommute) %>%
  rename(region = CensusId, value = MeanCommute)

choro               <- CountyChoropleth$new(mean_commute)
choro$title         <- "Mean Commute Times by County"
choro$ggplot_scale  <- scale_fill_brewer(name = "Time", palette = 2, drop = F)
choro$render()
```

## States plot
### `fiftystater`
```{r message = F, warning = F, fig.width = 10}

```

### `statebins`
```{r message = F, warning = F, fig.width = 10}
library(statebins)
```

### `rcstatebin`
```{r}
library(rcstatebin)

st_crosswalk <- tibble(State = state.name) %>%
  bind_cols(tibble(ST = state.abb)) %>% 
  bind_rows(tibble(State = "District of Columbia", ST = "DC")) %>%
  bind_rows(tibble(State = "Puerto Rico", ST = "PR"))
st_crosswalk$ST <- as.factor(st_crosswalk$ST)

stDemo   <- dfASC %>%
  group_by(State) %>%
  mutate_at(vars(Hispanic : Pacific), funs(. * TotalPop / 100)) %>%
  summarise_at(vars(TotalPop : Pacific), sum, na.rm = TRUE) %>%
  group_by(State) %>%
  mutate_at(vars(Men : Pacific), funs(. / TotalPop * 100)) %>%
  left_join(st_crosswalk) %>%
  gather(TotalPop:Pacific, key = "demo", value = "share")
  

statebin(data = stDemo,
  x = "ST",
  y = "share",
  facet = "demo",
  heading =  "<b>State Demographics</b>",
  footer = "<small>Cource: US Census Demogrpahic Data 2015",
#  colors = RColorBrewer::brewer.pal(5, 'PuRd'),
  control = 'dropdown'
)
```


### Hexbin from `geojsonio`
```{r message = F, warning = F, fig.width = 10}
# https://www.r-graph-gallery.com/328-hexbin-map-of-the-usa/
library(geojsonio)
library(broom)
library(rgeos)

spdf            <- geojson_read("us_states_hexgrid.geojson",  what = "sp")
spdf@data       <- spdf@data %>% mutate(google_name = gsub(" \\(United States\\)", "", google_name))
spdf_fortified  <- tidy(spdf, region = "google_name")

centers <- cbind.data.frame(data.frame(gCentroid(spdf, byid = TRUE), id = spdf@data$iso3166_2))

spdf_fortified <- left_join(spdf_fortified , stASC, by=c("id" = "State")) 
spdf_fortified$bin <- cut(spdf_fortified$MeanCommute,
                          breaks = c(seq(10, 35, by = 5), Inf),
                          labels = c(seq(10, 30, by = 5), "35+"),
                          include.lowest = TRUE
                          )
 

library(viridis)
my_palette <- rev(magma(8))[c(-1,-8)]

h <- ggplot() +
  geom_polygon(data = spdf_fortified, 
               aes(fill =  bin, x = long, y = lat, group = group)) +
  geom_text(data = centers, 
            aes(x = x, y = y, label = id), 
            color = "white", size = 3, alpha = 0.6
            ) +
  theme_void() +
  coord_map() +
  scale_fill_manual(values = my_palette, 
                    name="(units: minute)", 
                    guide = guide_legend(keyheight = unit(3, units = "mm"), 
                                         keywidth=unit(12, units = "mm"), 
                                         label.position = "bottom", 
                                         title.position = 'top', nrow=1
                                         ) 
                    ) +
  ggtitle( "Mean Commute Time" ) +
  labs(caption = "Cource: US Census Demogrpahic Data 2015") +
  theme(legend.position = c(0.5, 0.9),
        text = element_text(color = "#22211d"),
        plot.background = element_rect(fill = "#f5f5f2", color = NA),
        panel.background = element_rect(fill = "#f5f5f2", color = NA),
        legend.background = element_rect(fill = "#f5f5f2", color = NA),
        plot.title = element_text(size= 22, hjust=0.5, color = "#4e4d47",
                                  margin = margin(b = -0.1, t = 0.4, l = 2, unit = "cm")
                                  )
    )
 h
```


### `geofacet`
```{r message = F, warning = F, fig.width = 10}

```




















