
#### Load library
```{r message = F, warning = F}
library(tidyverse)
library(treemapify)
library(kableExtra)
library(patchwork)
```

### Read in Data
```{r message = F, warning = F}
raw_df <- read_csv("../data/week11_fifa_audience.csv")
```


### Color Table
```{r Color Table}
raw_df %>% 
  arrange(desc(gdp_weighted_share)) %>% 
  top_n(38) %>% 
  kable(format = "html",
        col.names = c("", "COUNTRY", "BODY",
                      "GLOBAL\nPOPULATION",
                      "WORLD CUP TV\nAUDIENCE",
                      "GDP-WEIGHTED\nAUDIENCE")) %>% 
  add_header_above(c(" " = 3, "IN 2010, SHARE OF ..." = 3)) %>% 
  column_spec(6, background = "#F5F5F5") %>% 
  kable_styling()
  
  #ggthemes::theme_fivethirtyeight() 
```


### GDP-weighted Audience Share
```{r GDP-weighted Audience Share}

# https://github.com/ysamano/TidyTuesday/blob/master/week_11/week_11.R
treemap1 <- raw_df %>% 
  ggplot(aes(area = tv_audience_share,
             subgroup = confederation,
             fill = gdp_weighted_share,
             label = country)) +
  geom_treemap(colour = "gray10") +
  geom_treemap_text(colour = "white", fontface = "italic", min.size = 3, reflow = T) +
  geom_treemap_subgroup_border(colour = "white", size = 2) +
  geom_treemap_subgroup_text(alpha = 0.6, colour = "black") +
  viridis::scale_fill_viridis(direction = -1) +
  labs(title = expression(paste("FIFA"^"®", " World Cup™ TV Audience Share 2010")),
       caption ="Source: FiveThirtyEight",
       fill = "GDP-weighted Audience Share (%)") +
  theme(plot.title = element_text(size = 20, face = "bold"),
        legend.position = "bottom")


#
```

### FIFA Audience Share (per capita)
```{r FIFA Audience Share per capita}
treemap2 <- raw_df %>% 
  mutate(tv_per_capita = tv_audience_share/population_share) %>% 
  ggplot(aes(area = tv_audience_share,
             subgroup = confederation,
             fill = tv_per_capita,
             label = country)) +
  geom_treemap(colour = "gray10") +
  geom_treemap_text(colour = "white", fontface = "italic", min.size = 3, reflow = T) +
  geom_treemap_subgroup_border(colour = "white", size = 2) +
  geom_treemap_subgroup_text(alpha = 0.6, colour = "black") +
  viridis::scale_fill_viridis(direction = -1) +
#  ggtitle(expression(paste("FIFA"^"®", " World Cup™ TV Audience Share 2010")))+
#  ggtitle(expression(paste0("FIFA"^"®", " World Cup™ TV Audience Share 2010")))
  labs(title = expression(paste("FIFA"^"®", " World Cup™ TV Audience Share 2010")),
       caption ="Source: FiveThirtyEight",
       fill = "TV Audience Share per capita") +
  theme(plot.title = element_text(size = 20, face = "bold"),
        legend.position = "bottom")
# library(plotly)
# ggplotly(treeplot2) 
# ggplotly not supported
# https://github.com/ropensci/plotly/issues/1031
ggsave("FAFA_TV.png", treemap2, height = 8, width = 10, units = "in", dpi = 300)
```

